# Define the version of the Docker Compose file format
version: '3'

# Define the services to be run
services:
  # Define the back-end service
  back-end:
    # Specify the build context and Dockerfile for the back-end service
    build:
      context: ./back-end
      dockerfile: Dockerfile
    # Specify the image name for the built back-end service
    image: softy-pinko-back-end:task4
    # Map port 5252 on the host to port 5252 on the back-end container
    ports:
      - 5252:5252

  # Define the front-end service
  front-end:
    # Specify the build context and Dockerfile for the front-end service
    build:
      context: ./front-end
      dockerfile: Dockerfile
    # Specify the image name for the built front-end service
    image: softy-pinko-front-end:task4
    # Map port 9000 on the host to port 9000 on the front-end container
    ports:
      - 9000:9000
    # Ensure the front-end service starts after the back-end service
    depends_on:
      - back-end